spring:
  application:
    name: demo-gateway-provider-goods
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848

feign:
  okhttp:
    enabled: true

server:
  port: 9080

logging:
  level:
    root: info
    com.demo.api: trace
  file:
    name: /log/demo-gateway-provider-goods.log
