spring:
  application:
    name: demo-gateway-consumer
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    openfeign:
      okhttp:
        enabled: true

server:
  port: 8090

logging:
  level:
    root: info
    cn.z.api: trace
  file:
    name: /log/demo-gateway-consumer.log
