spring:
  application:
    name: demo-feign-consumer
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848

feign:
  # 启用okhttp连接池
  okhttp:
    enabled: true

server:
  port: 8090

logging:
  level:
    root: info
  file:
    name: /log/demo-feign-consumer.log
