spring:
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB

server:
  port: 8080

id:
  machine-id: 0
  machine-bits: 8
  sequence-bits: 12

logging:
  level:
    root: info
  file:
    name: /log/demo-rest-provider.log
