spring:
  application:
    name: demo-seata-provider-test
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848

seata:
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      group: SEATA_GROUP
      application: seata-server
  tx-service-group: demo-seata
  service:
    vgroup-mapping:
      demo-seata: default
#  data-source-proxy-mode: XA

server:
  port: 9090

logging:
  level:
    root: info
  file:
    name: /log/demo-seata-provider-test.log
